categories:
  - name: Politica internazionale
    feeds:
      - https://www.foreignaffairs.com/rss.xml

  - name: AI e Tech
    feeds:
      - https://www.technologyreview.com/feed/
      - https://www.theverge.com/rss/index.xml
  
  - name: Antropologia e Scienze sociali
    feeds:
      - https://www.scientificamerican.com/feed/
      - https://www.science.org/rss/news_current.xml
lookback_hours: 24
max_per_category: 3
