name: Rassegna Flash

on:
  schedule:
    - cron: "30 6 * * *"  # 08:30 Europe/Rome
  workflow_dispatch:

jobs:
  rassegna:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Installazione dipendenze
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Esecuzione dello script
      - name: Run summarizer
        run: python rss_summarizer.py

      # 5. Mostra output dei file
      - name: Show output files
        run: cat output/*.txt || echo "No output generated"

      # 6. Invio dei link con preview a Telegram (solo righe contenenti link)
      - name: Send only links with preview to Telegram
        run: |
          for file in output/*.txt; do
            echo "Invio solo link con preview da $file a Telegram..."
            while IFS= read -r line; do
              # Invia solo righe che contengono un link
              if [[ "$line" =~ ^https?:// ]]; then
                curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
                  -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
                  -d text="$line"
                sleep 2
              fi
            done < "$file"
          done
